def reserved_keywords():
    reserved = {
        'if': 'IF',
        'else': 'ELSE',
        'elsif': 'ELSIF',
        'case': 'CASE',
        'endcase': 'ENDCASE',
        'begin': 'BEGIN',
        'end': 'END',
        'module': 'MODULE',
        'endmodule': 'ENDMODULE',
        'param': 'PARAM',
        'localparam': 'LOCALPARAM',
        'always': 'ALWAYS',
        'assign': 'ASSIGN',
        'for': 'FOR',
        'while': 'WHILE',
        'input': 'INPUT',
        'output': 'OUTPUT',
        'inout': 'INOUT',
        'pos': 'POS',
        'neg': 'NEG',
        'edge': 'EDGE',
        'signed': 'SIGNED',
        'reg': 'REG',
        'wire': 'WIRE',
    }
    return reserved


def get_tokens():
    tokens = (
        'SEP',
        'HASH',
        'SLASH',
        'DOT',
        'COM',
        'AND',
        'AT',
        'DOL',
        'EM',
        'QM',
        'NOT',
        'OR',
        'OSB',
        'CSB',
        'OB',
        'CB',
        'OWB',
        'CWB',
        'PLUS',
        'MINUS',
        'TIMES',
        'CLN',
        'SCLN',
        'EQ',
        'LT',
        'GT',
        # non literals
        'COMMENT',
        'ID',
        'NUMBER',
        'BIN_OPERATOR',
        'CONCATENATION_BODY',
        'SYNCH_ASSIGN',
        'COMPARISON_SYMBOL',
        'INTEGER',
    )
    return tokens
